apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    url: postgres-postgresql:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: polymarket
      sslmode: "disable"
