apiVersion: v1
kind: ConfigMap
metadata:
  name: polymarket-client-config
data:
  POLYMARKET_API_KEY: ""
  POLYMARKET_API_SECRET: ""
  POLYMARKET_PASSPHRASE: ""
  WALLET_ADDRESS: ""
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_TOPIC: "polymarket-messages"
---
apiVersion: v1
kind: Secret
metadata:
  name: polymarket-client-auth
stringData:
  POLYMARKET_API_KEY: ""
  POLYMARKET_API_SECRET: ""
  POLYMARKET_PASSPHRASE: ""
