apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: poly-sentiment  # Unique name for the new cluster
spec:
  image: flink-analytics:latest
  imagePullPolicy: IfNotPresent
  flinkVersion: v2_2
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    metrics.reporter.prom.port: "9249-9250"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "1024m"
      cpu: 1
  taskManager:
    resource:
      memory: "1024m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/poly.jar
    entryClass: org.apache.flink.examples.Sentiment
    parallelism: 1
    upgradeMode: stateless